### ISSUE TITLE
R Session Aborted  when using autoencoder

### ISSUE THREAD

**Issue by sawnaanwas** [bflammers/ANN2#12] opened 2020-01-04 02:09 UTC
I'm using ANN2::autoencoder() to remove peaks from data. However, the R session crashes randomly and I'm forced to start a new session when running the following lines of code. I have noticed when I run each line of code separately and wait a few seconds between running lines of code, it does not crash. 
Is there any way to avoid this issue?
thanks

"ts" : an atomic vector of length 1825 

AE <- autoencoder(ts, c(10,2,10), loss.type = 'pseudo-huber',
                  activ.functions = c('tanh','linear','tanh'),
                  batch.size = 8, optim.type = 'adam',
                  n.epochs = 40, val.prop = 0)
recX <- reconstruct(AE, ts)
ts2 <- as.vector(recX[["reconstructed"]])

**Comment by bflammers** [comment] 2020-01-04 20:45
Hi, 

In order to help you I need to be able to reproduce the error. Can you make a minimal reproducible example --> https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example

Thanks

**Comment by sawnaanwas** [comment] 2020-01-05 04:13
Hi, 

I have noticed that when I run the code, it crashes randomly every few times. 

library(ANN2)
set.seed(5)
ts <- rnorm(1825)
AE <- autoencoder(ts, c(10,2,10), loss.type = 'pseudo-huber',
                  activ.functions = c('tanh','linear','tanh'),
                  batch.size = 8, optim.type = 'adam',
                  n.epochs = 40, val.prop = 0)
recX <- reconstruct(AE, ts)
ts2 <- as.vector(recX[["reconstructed"]])

So, I put it inside a for loop, where each time that I source the code below, it crashes after a few iterations.

library(ANN2)
set.seed(5)
ts <- rnorm(1825)
for(i in seq(1:10)){
  AE <- autoencoder(ts, c(10,2,10), loss.type = 'pseudo-huber',
                    activ.functions = c('tanh','linear','tanh'),
                    batch.size = 8, optim.type = 'adam',
                    n.epochs = 40, val.prop = 0)
  recX <- reconstruct(AE, ts)
  ts2 <- as.vector(recX[["reconstructed"]])
}

hope it helps,
thanks

**Comment by bflammers** [comment] 2020-01-05 20:13
Hi, 

Unfortunately, I cannot reproduce the error. On my machine the loop run for any number of iterations and it does not crash. 

My (very rough) initial guess is that this is not a bug in ANN2, but that something goes wrong on the Rcpp level or R level in constructing a Rcpp module object. Do you get an error message? 

I am afraid these kind of things are hard to reproduce across machines and track down...Try updating Rcpp and/or your R version and see if that helps. If that does not work, I am afraid I cannot help.

**Comment by sawnaanwas** [comment] 2020-01-06 01:23
Hi, 

Thank you for your response. Rcpp was up to date, and I updated R/ RStudio/all packages. But unfortunately, it still crashes. And there is no error message. 
My machine is MacBook Pro, Quad-Core Core i5, 1.4 GHz, Memory 8 GB, OS Catalina 10.15.2. 
 thanks

**Comment by evanmunro** [comment] 2020-05-17 19:34
I am also having this same problem with ANN2, with the same Mac OS Catalina setup as the original poster. I can't reproduce the error on Linux, and don't get any error messages. 

My use case crashes using ANN2::neuralnetwork in a for loop. But I can reproduce the error when using the original poster's for loop. 

I don't have issues with any other packages that I am using that use Rcpp.

**Comment by bflammers** [comment] 2020-12-01 22:48
I was able to reproduce the error and locate the memory leak. The fix is included in #22 

v2.3.4 that includes the fix is on its way to CRAN now.

**Closed by bflammers** 2020-12-01 22:48 UTC
